package com.exam;
// Generated May 30, 2018 7:24:46 PM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private String user;
     private String name;
     private String password;
     private String email;
     private int otp;

    public Employee() {
    }

	
    public Employee(String user) {
        this.user = user;
    }
    public Employee(String user, String name, String password, String email, int otp) {
       this.user = user;
       this.name = name;
       this.password = password;
       this.email = email;
       this.otp = otp;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getOtp() {
        return this.otp;
    }
    
    public void setOtp(int otp) {
        this.otp = otp;
    }




}


